name: Publish UI Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          token: ${{ secrets.DEPLOY_UI_BUILD_BOT }}
      - run: |
          git config --global user.email "buildUI.bot@c3.ai"
          git config --global user.name "Build UI Bot"
          npm install
          npm run build
          git commit -a -m "Update UI Build"
          git push
